### ISSUE TITLE
Clean Fresh Install Reagent Banker Wrong Gossip

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#259] opened 2024-04-20 11:47 UTC
Reagent Banker using Transmog Gossips on fresh clean install.

I remember vaguely there being an SQL fix in release notes somewhere but all adjustments should be bundled in fresh clean installs as pre-ran SQL.

**Comment by StraysFromPath** [comment] 2024-04-20 11:51
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/245

It's here. This fix was never applied to master.

**Comment by StraysFromPath** [comment] 2024-04-20 11:56
UPDATE creature
SET id = 290011
WHERE id = 190011;

This should be added to the update script or something. Effectively I had old/dead/broken NPCs spawned because AzerothCore co-opted the ID.

Then due to client-side cache data it looked like the banker but had the wrong gossip.

This would be extremely confusing for a low-tech user who wasn't paying attention to the issue log.

**Comment by ZhengPeiRu21** [comment] 2024-04-23 17:07
Thank you for the issue report. This fix has already been merged and is included in the latest repack. I'm unable to reproduce the issue; I think it was due to your old cached data. Please let me know if you're able to reproduce this and I will re-open the issue.

**Closed by ZhengPeiRu21** 2024-04-23 17:07 UTC
