### ISSUE TITLE
Question about 2 worldserver console errors

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#273] opened 2024-05-23 14:29 UTC
I've compiled the latest azerothcore with npcbots today with the latest version of your module.
I'm getting 2 errors when I start up the server in the worldserver console.

Spell (Id: 90003, effIndex: 0) listed in `spell_target_position` does not have target TARGET_DEST_DB (17).
Script named 'spell_gen_consumption' is not assigned in the database.

I found out spell 90003 is 'Bombard Slime'. I also found it in 'naxx40_spells.sql'
So I assume it's part of the new naxx update.
I can't find a TARGET_DEST_DB column anywhere however, I can't figure out what the problem is or how to fix it.

the spell_gen_consumption error comes up during 'loading scripts'
I've looked around a bit, I don't see it in spell_script_names
maybe that's where it was expected to be found, again I don't understand this all well enough.

Maybe these errors don't cause any harm, but I really like to not get any errors when I start up the server so I'm hoping there is a way to get rid of them.

**Comment by ZhengPeiRu21** [comment] 2024-05-29 20:04
Thanks for reporting the issue. This was caused by an ID collection between an re-implemented Onyxia spell and a re-implemented Naxx 40 spell. This should be fixed as of https://github.com/ZhengPeiRu21/mod-individual-progression/commit/9733b28aa0c5e1597989c6e497d01cb16f4ff623.

**Comment by Grimfeather** [comment] 2024-05-30 01:04
this fixed the first error, but not the 2nd one.

Script named 'spell_gen_consumption' is not assigned in the database.

https://i.gyazo.com/ed6ae1dbbac4fefe378d8c49e496e5a6.png

**Comment by ZhengPeiRu21** [comment] 2024-05-30 02:53
I apologize for closing the issue prematurely. It looks like consumption was broken by this upstream commit (https://github.com/ZhengPeiRu21/azerothcore-wotlk/commit/d44c8990c1436f941c181d603f11ee5d1bf95005) and needs to be fixed.

**Comment by ZhengPeiRu21** [comment] 2024-05-30 15:58
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/2ce9936217dd19843bc00792e9d6f4a52a1ce79a.

**Closed by ZhengPeiRu21** 2024-05-30 15:58 UTC

**Comment by Grimfeather** [comment] 2024-05-30 16:26
this removed the spell_gen_consumption error, but another error took it's place.

https://i.gyazo.com/f210d807d55d911316fa44ef66050318.png

Script named 'spell_four_horsemen_consumption' is not assigned in the database.

**Comment by ZhengPeiRu21** [comment] 2024-05-30 22:19
> this removed the spell_gen_consumption error, but another error took it's place.
> 
> https://i.gyazo.com/f210d807d55d911316fa44ef66050318.png
> 
> Script named 'spell_four_horsemen_consumption' is not assigned in the database.

I'm not seeing that error in my fresh build. Did you recompile with the latest version? There should no longer be any references in the code to spell_four_horsemen_consumption.

**Comment by Grimfeather** [comment] 2024-05-30 23:33
My bad. I only applied the changes from the sql.
I did a recompile. I no longer get the errors with the new exe files.
all good now

**Comment by zhbur** [comment] 2024-06-10 20:44
Just made a fresh build and another unassigned script popped up:

Script named 'spell_four_horsemen_mark' is not assigned in the database.
