### ISSUE TITLE
Nerf Values for Damage flipped?

### ISSUE THREAD

**Issue by Day36512** [ZhengPeiRu21/mod-individual-progression#133] opened 2023-05-01 15:58 UTC
Hey at least for vanilla your Power modifiers seem to be flipped. 0 is now 100% damage and 1 is now miss all the time.

**Comment by ZhengPeiRu21** [comment] 2023-05-01 16:28
Oops! Thank you for catching that mistake. I will submit a fix.

**Comment by ZhengPeiRu21** [comment] 2023-05-01 16:46
Thanks again for noticing this error! This should now be fixed with https://github.com/ZhengPeiRu21/mod-individual-progression/commit/1fd631baab1ea159a6c0e5b6334e438cb390f752.

**Comment by Day36512** [comment] 2023-05-01 20:10
Hey sorry so it seems like the config option is not affecting anything now.

**Comment by Day36512** [comment] 2023-05-01 20:17
nvm just ignore me. Sorry.

**Comment by ZhengPeiRu21** [comment] 2023-05-02 00:05
> Hey sorry so it seems like the config option is not affecting anything now.

Could you share how you are testing? I just re-tested and it seems to be working as designed - at level 10, spells do 100% of damage regardless of config value. At level 60, they deal half damage with a config value of 0.5, and 10% damage with a config value of 0.1. Levels in between appear to be scaling properly.

**Comment by ZhengPeiRu21** [comment] 2023-06-15 13:45
It seems that this is all resolved, so I will be closing this issue, but please comment if you continue to see any issue and I will reopen it!

**Closed by ZhengPeiRu21** 2023-06-15 13:45 UTC
