### ISSUE TITLE
Vanilla Onyxia  autobalance

### ISSUE THREAD

**Issue by aluveitie** [ZhengPeiRu21/mod-individual-progression#263] opened 2024-04-28 10:06 UTC
I'm running recent Azerothcore + mod-individual-progression + mod-autobalance

So far it was working almost perfectly, though Onyxia does not scale at level 60. 
I've also checked MC and there scaling is working.

Any hints how to fix that?

![Screenshot 2024-04-28 at 12 00 33](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/61966108/53f1548f-2da0-4e4e-80fd-618039957285)
![Screenshot 2024-04-28 at 12 01 05](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/61966108/ab1ad726-0043-4da7-a4d4-e4542bd7f36f)

**Comment by geekodot** [comment] 2024-05-10 20:24
Can confirm I am running into this issue as well. Tried enabling level scaling, but does not seem to be the cause.
Running most recent Azerothcore with Playerbots, individual progression and autobalance.

**Comment by Kabakaylen** [comment] 2024-06-03 20:03
Check through this discussion for some tidbits. You need to change the raid difficulty setting, its a bit bugg.

https://github.com/ZhengPeiRu21/mod-individual-progression/issues/214

**Comment by geekodot** [comment] 2024-06-12 16:31
@Kabakaylen 
Changing the difficulty through the method described here puts me in the right version of the instance, but it still doesn't seem to scale down to for example one player when I enter with just my GM character. Any edits I need to make to autobalance to get it to scale? ( Ony still has more than a million HP )

**Comment by Kabakaylen** [comment] 2024-06-12 19:21
Are you running Trickerer fork of AB? You need to run that with if you're using NPC bots, he's modified it to work.

https://github.com/trickerer?tab=repositories

**Comment by geekodot** [comment] 2024-06-24 17:52
I've tested setting up a new instance of AzerothCore running just Autobalance and Individual Progression with default configurations and while I can enter the correct instance, they do not seem to scale down. Wonder if it might be the autobalance mod not recognizing the 40-player Heroic raid group.

**Comment by webtectonics** [comment] 2024-06-27 13:33
I'm running into this same exact issue.  Did you ever figure anything out?

**Comment by aluveitie** [comment] 2024-06-27 13:37
I think the same issue also applies for the level 60 Naxx instance, we weren't even able to really do trash mobs with a group of 3.

**Comment by Kabakaylen** [comment] 2024-06-28 18:11
I can confirm that updating to the latest version of AB has broken this. I can no longer get AB to scale correct despite being in the correct 40m (level 60) version.

**Comment by atrapalis** [comment] 2024-06-28 21:24
@Kabakaylen @webtectonics I can also confirm that updating autobalance broke this for my server.

The issue appears somewhere between these two commits:
https://github.com/trickerer/mod-autobalance/compare/190e67dc345bfb4ec59b6cce5149893613e8cff0..c25441c0e391d763729950fc6639af9c8937338a

In other words, Onyxia works for me as described in #214 when compiled using this version of autobalance:
https://github.com/trickerer/mod-autobalance/tree/190e67dc345bfb4ec59b6cce5149893613e8cff0

**Comment by atrapalis** [comment] 2024-06-29 19:25
I have done some more testing and have prepared a fix for this in pull request #298.

The issue is that the new autobalance update determines an acceptable level scaling range based on LFG entry data. There is no LFG dungeon entry for level 60 Onyxia which is added with this mod, so autobalance calculates the acceptable level scaling ranges based on one of the level 80 LFG entries. Because of this autobalance disables scaling for all creatures lower than level 68 (minimum level for mobs based on the level 80 target), which explains why the screenshots above indicate "Total Creatures in map: 0"

To fix this I have added a new LFG entry to `lfgdungeon_dbc` set for level 60.

**Comment by webtectonics** [comment] 2024-06-30 13:57
Awesome! I ran the SQL scripts and that fixed it for me, at least in the 15 minutes of testing that I did. We have a raid planned for Tuesday, I'll let you know if I run into any snags. Thank you!!

**Comment by Kabakaylen** [comment] 2024-06-30 22:00
Thank you @atrapalis your SQL update fixed it, great!

**Comment by aluveitie** [comment] 2024-07-01 04:24
@atrapalis could you also make a similar fix for level 60 Naxx? It suffers from the same issue I think.

**Comment by geekodot** [comment] 2024-07-01 16:31
Can confirm this also fixed Onyxia for me.

**Comment by ZhengPeiRu21** [comment] 2024-07-01 19:05
Thanks atrapalis for your fix! I'll go ahead and close this issue since this is now resolved.

**Closed by ZhengPeiRu21** 2024-07-01 19:05 UTC

**Comment by webtectonics** [comment] 2024-07-08 19:54
Is there an issue with level 60 Naxx as well that @aluveitie mentioned? We are quickly approaching Naxx so I just wanted to check.
