### ISSUE TITLE
Compact Harvest Reaper (entry 2676)

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#147] opened 2023-07-16 20:57 UTC
Whirleygig in the Barrens and engineers around Gerenzo in Stonetalon mountains summon a Compact Harvest Reaper. (entry 2676) 
They should do this,  but the problem is that this Reaper is level 40-41.
This compact harvest reaper in Stonetalon should be level 21-22.

There are 3 npc's that summon a compact harvest reaper.
https://www.wowhead.com/wotlk/spell=7979/compact-harvest-reaper#used-by-npc

The database only has 1 version, the lvl 40-41 version that a Venture Co. Tinkerer in STV should summon.

**Comment by ZhengPeiRu21** [comment] 2023-07-17 23:03
Thank you for reporting the issue. This is a duplicate of https://github.com/ZhengPeiRu21/mod-individual-progression/issues/64. This is an AzerothCore bug that needs to be resolved in the core - please see the linked issue in the comment.

**Closed by ZhengPeiRu21** 2023-07-17 23:03 UTC
