### ISSUE TITLE
Still gaining levels

### ISSUE THREAD

**Issue by cutdachez** [ZhengPeiRu21/mod-individual-progression#277] opened 2024-06-03 13:26 UTC
1- 60 went perfect. Got to 60 and xp and level gains stopped till progression tiers were done. Reached level 70.  Xp and levels is still being gained. Even though progression tier has not be completed.

**Comment by Grimfeather** [comment] 2024-06-03 20:06
strange. I don't have this problem.
I'm currently level 70 with my raid team and everyone stopped gaining xp.
pretty much everyone did get a bit of extra xp, probably from a quest turn in
example being a hunter I tested this with, she's at 7655/1523800
but after killing a level 67 enemy in Netherstorm it was still the same.

could you provide more information?
- you gaining xp from quests? from mob kills?
- if you're able to open the database with heidiSQL, which progression tier are you in? 
  you can find it in acore_characters/character_settings 
- which version of this mod are you using? recent? preview build?
- compiled by yourself or a repack by someone? which repack?

**Comment by cutdachez** [comment] 2024-06-03 20:22
could you provide more information?

    you gaining xp from quests? from mob kills? Both

    if you're able to open the database with heidiSQL, which progression tier are you in? Says 12 (mod individual Progression)
    you can find it in acore_characters/character_settings

    which version of this mod are you using? recent? preview build? most recent build

    compiled by yourself or a repack by someone? which repack? Built myself

As far as tier I have actually done. Finished Nax, And still doing attunes for TBC stuff like Kara. Have not killed first boss. Have gained couple levels just doing attunement quest. Looking at the tier list. Seems it has me doing WOTLK Nax and not vanilla

**Comment by StraysFromPath** [comment] 2024-06-05 17:50
> could you provide more information?
> 
> ```
> you gaining xp from quests? from mob kills? Both
> 
> if you're able to open the database with heidiSQL, which progression tier are you in? Says 12 (mod individual Progression)
> you can find it in acore_characters/character_settings
> 
> which version of this mod are you using? recent? preview build? most recent build
> 
> compiled by yourself or a repack by someone? which repack? Built myself
> ```
> 
> As far as tier I have actually done. Finished Nax, And still doing attunes for TBC stuff like Kara. Have not killed first boss. Have gained couple levels just doing attunement quest. Looking at the tier list. Seems it has me doing WOTLK Nax and not vanilla

If you finished naxx then you have entered the TBC phase and your level cap was increased to 70.

**Comment by cutdachez** [comment] 2024-06-06 00:22
> > could you provide more information?
> > ```
> > you gaining xp from quests? from mob kills? Both
> > 
> > if you're able to open the database with heidiSQL, which progression tier are you in? Says 12 (mod individual Progression)
> > you can find it in acore_characters/character_settings
> > 
> > which version of this mod are you using? recent? preview build? most recent build
> > 
> > compiled by yourself or a repack by someone? which repack? Built myself
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As far as tier I have actually done. Finished Nax, And still doing attunes for TBC stuff like Kara. Have not killed first boss. Have gained couple levels just doing attunement quest. Looking at the tier list. Seems it has me doing WOTLK Nax and not vanilla
> 
> If you finished naxx then you have entered the TBC phase and your level cap was increased to 70.

Right, But I continued to gain xp past 70. I quit once I hit 75. Until can figure out issue

**Comment by cutdachez** [comment] 2024-06-06 00:26
> It sounds like something occurred that placed you in a post-TBC phase. Was there a certain point at which you began gaining experience again, or did you continue to gain experience at soon as you hit 70? Please let me know if you're able to replicate the issue.

Continued once I hit 70 xp continued to roll in. Looking at the dp for tier I am in or level. It has me at 12. According to list that is after Nax Wotlk. So it seems for some reason. It gave me credit for wrong Nax. 

I still have that server I can run. But, I started fresh to see if it happens again. In case I added or changed something I should not have. 

Curious if it maybe because I was playing on account with gm permissions.

**Comment by cutdachez** [comment] 2024-06-09 13:55
Ok, So I think I may have found the issue with Nax tier, Least on my side of it. Seems that Strat portal takes u to one version of nax. And The nax portal in plaguewwod takes u to a different version of Nax,.

Maybe someone can verify this.

**Comment by ZhengPeiRu21** [comment] 2024-06-10 19:24
> Ok, So I think I may have found the issue with Nax tier, Least on my side of it. Seems that Strat portal takes u to one version of nax. And The nax portal in plaguewwod takes u to a different version of Nax,.
> 
> Maybe someone can verify this.

That sounds like something that definitely should be fixed. Any WotLK version of Naxx should have level 80 enemies. Does entering Naxx through either of these means have enemies at level 80 rather than 60?

**Comment by cutdachez** [comment] 2024-06-10 20:21
> > Ok, So I think I may have found the issue with Nax tier, Least on my side of it. Seems that Strat portal takes u to one version of nax. And The nax portal in plaguewwod takes u to a different version of Nax,.
> > Maybe someone can verify this.
> 
> That sounds like something that definitely should be fixed. Any WotLK version of Naxx should have level 80 enemies. Does entering Naxx through either of these means have enemies at level 80 rather than 60?

In the strat and plaguewood portal they are level 60 - 63. Which I think is fine for classic tier que. Once you into thru teh wotlk tier npcs are level 80 +. Which I think is correct. 

Only real issue I see. Id the tier problem with Start entrance and Plaguewood entrance. 

FYI: I did not complete Nax in wotlk tier yet. So can not say what the tier reward is correct or not for that version.

**Comment by ZhengPeiRu21** [comment] 2024-08-20 15:57
Given that this seems to be a one-off issue, I'm going to go ahead and close this. If you encounter a similar problem in the future or find a way to reproduce it, please let me know!

**Closed by ZhengPeiRu21** 2024-08-20 15:57 UTC
