### ISSUE TITLE
Gurubashi Arena not a PvP Zone

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#224] opened 2024-01-15 16:17 UTC
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/a48d7f1b-faad-4bf2-9f35-36c86d8a13eb)

Player is not flagged for pvp or FFA inside of gurubashi arena.

Expected behaviour is this bot would fight/attack.

**Comment by Grimfeather** [comment] 2024-01-24 23:49
just tested this.
I do get pvp flagged.
just outside: https://i.gyazo.com/dcfc685a6e02292b3e68af82b806fae2.jpg
inside: https://i.gyazo.com/09c18e53e2612cbd7c74c4c9aee0b1ac.jpg

notice the sword icon left of my character picture.

Maybe you are playing with GM on? because when I turn GM on I'm no longer flagged.

**Comment by ZhengPeiRu21** [comment] 2024-03-04 15:38
Thanks Grimfeather for testing. I also wasn't able to reproduce this issue. I'm going to close this issue for now, but feel free to re-open it if you feel necessary.

**Closed by ZhengPeiRu21** 2024-03-04 15:38 UTC
