### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#175] opened 2023-08-26 11:52 UTC
Did a fresh install and got these errors on booting up the worldserver.

![console_errors](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/100827869/fd874a93-ded3-4780-9fbc-4111a0421183)

**Comment by ZhengPeiRu21** [comment] 2023-08-29 15:09
Thank you for your issue report. The Item warnings are intentional - the module changes many items back to their Vanilla classes and subclasses, such as profession reagents that were changed to junk in WotLK. AzerothCore incorrectly reports a warning here even when EnforceItemAttributes is set to 0. I'm planning to fix this upstream so that it no longer gives warnings in these cases.

The creature_addon warning is not intended and probably caused by some old data. It can be safely ignored but would be nice to resolve. I'll look into getting it cleaned up!

**Comment by ZhengPeiRu21** [comment] 2023-09-03 16:28
The console warnings from creature_addon should be resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/b1986264ae4c939f44ab46ad38d95a43c0f7f156. I'll keep this issue open to track when the AC upstream fix will be merged that will get rid of the other warnings.

**Comment by ZhengPeiRu21** [comment] 2023-09-19 15:55
With https://github.com/azerothcore/azerothcore-wotlk/pull/16508 merged into AC master, these errors should no longer appear.

**Closed by ZhengPeiRu21** 2023-09-19 15:55 UTC
